[2024-11-30T08:58:02.493+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:58:02.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T08:58:02.499+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:02.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:58:02.588+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:02.577+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T08:58:02.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:58:02.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.141 seconds
[2024-11-30T08:58:33.268+0000] {processor.py:161} INFO - Started process (PID=500) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:58:33.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T08:58:33.278+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:33.277+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:58:33.483+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:33.458+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T08:58:33.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:58:33.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.291 seconds
[2024-11-30T08:59:04.422+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:59:04.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T08:59:04.434+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:04.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:59:04.648+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:04.631+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T08:59:04.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:59:04.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.306 seconds
[2024-11-30T08:59:35.561+0000] {processor.py:161} INFO - Started process (PID=557) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:59:35.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T08:59:35.567+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:35.566+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:59:35.647+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:35.634+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T08:59:35.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T08:59:35.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.155 seconds
[2024-11-30T09:00:06.493+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:00:06.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:00:06.511+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:06.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:00:06.633+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:06.615+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:00:06.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:00:06.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.208 seconds
[2024-11-30T09:00:37.771+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:00:37.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:00:37.781+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:37.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:00:37.969+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:37.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:00:37.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:00:38.033+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.277 seconds
[2024-11-30T09:01:08.470+0000] {processor.py:161} INFO - Started process (PID=650) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:01:08.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:01:08.475+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:08.474+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:01:08.547+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:08.537+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:01:08.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:01:08.573+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.110 seconds
[2024-11-30T09:01:38.824+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:01:38.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:01:38.827+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:38.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:01:38.907+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:38.897+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:01:38.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:01:38.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.123 seconds
[2024-11-30T09:02:09.141+0000] {processor.py:161} INFO - Started process (PID=706) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:02:09.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:02:09.153+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:09.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:02:09.370+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:09.313+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:02:09.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:02:09.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.339 seconds
[2024-11-30T09:02:39.859+0000] {processor.py:161} INFO - Started process (PID=732) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:02:39.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:02:39.869+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:39.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:02:40.047+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:40.024+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:02:40.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:02:40.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.268 seconds
[2024-11-30T09:03:10.478+0000] {processor.py:161} INFO - Started process (PID=758) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:03:10.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:03:10.488+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:10.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:03:10.668+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:10.643+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:03:10.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:03:10.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.261 seconds
[2024-11-30T09:03:40.994+0000] {processor.py:161} INFO - Started process (PID=784) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:03:40.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:03:40.999+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:40.998+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:03:41.085+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:41.074+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:03:41.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:03:41.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.142 seconds
[2024-11-30T09:04:11.858+0000] {processor.py:161} INFO - Started process (PID=823) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:04:11.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:04:11.874+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:11.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:04:12.062+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:12.042+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:04:12.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:04:12.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.286 seconds
[2024-11-30T09:04:42.518+0000] {processor.py:161} INFO - Started process (PID=853) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:04:42.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:04:42.531+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:42.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:04:42.722+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:42.699+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:04:42.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:04:42.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.272 seconds
[2024-11-30T09:05:13.082+0000] {processor.py:161} INFO - Started process (PID=881) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:05:13.083+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:05:13.086+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:13.085+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:05:13.162+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:13.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:05:13.167+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:05:13.194+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.119 seconds
[2024-11-30T09:05:43.817+0000] {processor.py:161} INFO - Started process (PID=919) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:05:43.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:05:43.822+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:43.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:05:43.907+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:43.897+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:05:43.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:05:43.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.134 seconds
[2024-11-30T09:06:14.747+0000] {processor.py:161} INFO - Started process (PID=956) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:06:14.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:06:14.757+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:14.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:06:14.850+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:14.838+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:06:14.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:06:14.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.145 seconds
[2024-11-30T09:06:45.091+0000] {processor.py:161} INFO - Started process (PID=983) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:06:45.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:06:45.100+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:45.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:06:45.253+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:45.228+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:06:45.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:06:45.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.223 seconds
[2024-11-30T09:07:15.653+0000] {processor.py:161} INFO - Started process (PID=1016) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:07:15.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:07:15.665+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:15.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:07:15.847+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:15.823+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:07:15.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:07:15.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.270 seconds
[2024-11-30T09:07:46.386+0000] {processor.py:161} INFO - Started process (PID=1043) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:07:46.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:07:46.396+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:46.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:07:46.590+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:46.564+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:07:46.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:07:46.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.287 seconds
[2024-11-30T09:08:17.409+0000] {processor.py:161} INFO - Started process (PID=1070) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:08:17.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:08:17.419+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:17.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:08:17.626+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:17.601+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:08:17.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:08:17.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.305 seconds
[2024-11-30T09:08:48.724+0000] {processor.py:161} INFO - Started process (PID=1119) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:08:48.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:08:48.727+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:48.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:08:48.779+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:48.766+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:08:48.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:08:48.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.086 seconds
[2024-11-30T09:09:19.386+0000] {processor.py:161} INFO - Started process (PID=1166) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:09:19.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:09:19.399+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:19.397+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:09:19.607+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:19.583+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:09:19.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:09:19.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.310 seconds
[2024-11-30T09:09:50.185+0000] {processor.py:161} INFO - Started process (PID=1193) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:09:50.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:09:50.190+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:50.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:09:50.270+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:50.256+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:09:50.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:09:50.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.129 seconds
[2024-11-30T09:10:21.218+0000] {processor.py:161} INFO - Started process (PID=1220) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:10:21.222+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:10:21.226+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:21.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:10:21.398+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:21.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:10:21.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:10:21.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.254 seconds
[2024-11-30T09:10:52.222+0000] {processor.py:161} INFO - Started process (PID=1247) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:10:52.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:10:52.236+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:52.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:10:52.386+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:52.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:10:52.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:10:52.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.234 seconds
[2024-11-30T09:11:23.426+0000] {processor.py:161} INFO - Started process (PID=1274) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:11:23.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:11:23.436+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:23.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:11:23.614+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:23.588+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:11:23.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:11:23.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.275 seconds
[2024-11-30T09:11:53.899+0000] {processor.py:161} INFO - Started process (PID=1307) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:11:53.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:11:53.903+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:53.903+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:11:54.034+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:54.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:11:54.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:11:54.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.201 seconds
[2024-11-30T09:12:24.909+0000] {processor.py:161} INFO - Started process (PID=1338) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:12:24.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:12:24.914+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:24.914+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:12:25.010+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:24.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:12:25.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:12:25.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.148 seconds
[2024-11-30T09:12:55.220+0000] {processor.py:161} INFO - Started process (PID=1357) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:12:55.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:12:55.225+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:55.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:12:55.306+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:55.294+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:12:55.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:12:55.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.122 seconds
[2024-11-30T09:13:26.268+0000] {processor.py:161} INFO - Started process (PID=1384) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:13:26.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:13:26.294+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:26.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:13:26.409+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:26.390+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:13:26.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:13:26.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.232 seconds
[2024-11-30T09:13:56.899+0000] {processor.py:161} INFO - Started process (PID=1411) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:13:56.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:13:56.913+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:56.911+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:13:57.129+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:57.097+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:13:57.140+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:13:57.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.333 seconds
[2024-11-30T09:14:28.159+0000] {processor.py:161} INFO - Started process (PID=1438) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:14:28.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:14:28.169+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:28.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:14:28.408+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:28.385+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:14:28.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:14:28.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.331 seconds
[2024-11-30T09:14:59.422+0000] {processor.py:161} INFO - Started process (PID=1465) to work on /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:14:59.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/get_weather.py for tasks to queue
[2024-11-30T09:14:59.433+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:59.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:14:59.616+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:59.590+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/get_weather.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/get_weather.py", line 10, in <module>
    API_KEY = Variable.get('OPEN_WEATHER_API_KEY')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable OPEN_WEATHER_API_KEY does not exist'
[2024-11-30T09:14:59.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/get_weather.py
[2024-11-30T09:14:59.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/get_weather.py took 0.278 seconds
