[2024-11-30T08:58:03.987+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:58:04.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T08:58:04.072+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:04.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:58:06.636+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:06.602+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:58:06.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:58:06.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 2.933 seconds
[2024-11-30T08:58:37.035+0000] {processor.py:161} INFO - Started process (PID=514) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:58:37.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T08:58:37.041+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:37.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:58:38.142+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:58:38.128+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:58:38.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:58:38.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.156 seconds
[2024-11-30T08:59:08.633+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:59:08.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T08:59:08.637+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:08.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:59:09.505+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:09.489+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:59:09.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:59:09.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.924 seconds
[2024-11-30T08:59:40.542+0000] {processor.py:161} INFO - Started process (PID=571) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:59:40.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T08:59:40.552+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:40.550+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:59:42.191+0000] {logging_mixin.py:188} INFO - [2024-11-30T08:59:42.182+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T08:59:42.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T08:59:42.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.697 seconds
[2024-11-30T09:00:13.133+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:00:13.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:00:13.147+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:13.145+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:00:14.021+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:14.005+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:00:14.028+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:00:14.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.961 seconds
[2024-11-30T09:00:44.503+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:00:44.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:00:44.516+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:44.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:00:45.376+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:00:45.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:00:45.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:00:45.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.922 seconds
[2024-11-30T09:01:15.908+0000] {processor.py:161} INFO - Started process (PID=659) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:01:15.915+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:01:15.920+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:15.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:01:18.277+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:18.263+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:01:18.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:01:18.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 2.411 seconds
[2024-11-30T09:01:49.227+0000] {processor.py:161} INFO - Started process (PID=688) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:01:49.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:01:49.233+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:49.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:01:51.074+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:01:51.050+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:01:51.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:01:51.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 2.027 seconds
[2024-11-30T09:02:21.555+0000] {processor.py:161} INFO - Started process (PID=711) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:02:21.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:02:21.561+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:21.560+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:02:22.313+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:22.302+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:02:22.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:02:22.358+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.810 seconds
[2024-11-30T09:02:52.591+0000] {processor.py:161} INFO - Started process (PID=737) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:02:52.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:02:52.604+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:52.601+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:02:53.398+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:02:53.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:02:53.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:02:53.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.864 seconds
[2024-11-30T09:03:24.560+0000] {processor.py:161} INFO - Started process (PID=763) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:03:24.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:03:24.658+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:24.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:03:26.525+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:26.513+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:03:26.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:03:26.598+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 2.055 seconds
[2024-11-30T09:03:56.959+0000] {processor.py:161} INFO - Started process (PID=795) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:03:56.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:03:56.969+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:56.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:03:58.194+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:03:58.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:03:58.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:03:58.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.295 seconds
[2024-11-30T09:04:28.747+0000] {processor.py:161} INFO - Started process (PID=828) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:04:28.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:04:28.757+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:28.755+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:04:29.571+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:04:29.556+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:04:29.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:04:29.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.884 seconds
[2024-11-30T09:05:00.201+0000] {processor.py:161} INFO - Started process (PID=861) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:05:00.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:05:00.211+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:00.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:05:01.497+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:01.479+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:05:01.502+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:05:01.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.349 seconds
[2024-11-30T09:05:31.761+0000] {processor.py:161} INFO - Started process (PID=894) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:05:31.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:05:31.770+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:31.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:05:33.314+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:05:33.299+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:05:33.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:05:33.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.595 seconds
[2024-11-30T09:06:03.764+0000] {processor.py:161} INFO - Started process (PID=940) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:06:03.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:06:03.779+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:03.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:06:05.275+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:05.257+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:06:05.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:06:05.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.567 seconds
[2024-11-30T09:06:35.731+0000] {processor.py:161} INFO - Started process (PID=970) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:06:35.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:06:35.749+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:35.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:06:36.559+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:06:36.547+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:06:36.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:06:36.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.891 seconds
[2024-11-30T09:07:07.256+0000] {processor.py:161} INFO - Started process (PID=1003) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:07:07.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:07:07.265+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:07.265+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:07:08.130+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:08.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:07:08.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:07:08.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.945 seconds
[2024-11-30T09:07:38.837+0000] {processor.py:161} INFO - Started process (PID=1030) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:07:38.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:07:38.849+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:38.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:07:39.896+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:07:39.888+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:07:39.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:07:39.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.109 seconds
[2024-11-30T09:08:10.934+0000] {processor.py:161} INFO - Started process (PID=1063) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:08:10.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:08:10.946+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:10.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:08:12.001+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:11.987+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:08:12.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:08:12.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.118 seconds
[2024-11-30T09:08:42.641+0000] {processor.py:161} INFO - Started process (PID=1102) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:08:42.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:08:42.645+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:42.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:08:43.071+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:08:43.062+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:08:43.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:08:43.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.469 seconds
[2024-11-30T09:09:13.483+0000] {processor.py:161} INFO - Started process (PID=1154) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:09:13.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:09:13.489+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:13.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:09:14.333+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:14.323+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:09:14.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:09:14.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.890 seconds
[2024-11-30T09:09:44.778+0000] {processor.py:161} INFO - Started process (PID=1180) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:09:44.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:09:44.792+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:44.790+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:09:45.942+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:09:45.931+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:09:45.946+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:09:45.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.201 seconds
[2024-11-30T09:10:16.213+0000] {processor.py:161} INFO - Started process (PID=1204) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:10:16.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:10:16.226+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:16.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:10:17.107+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:17.098+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:10:17.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:10:17.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.937 seconds
[2024-11-30T09:10:48.056+0000] {processor.py:161} INFO - Started process (PID=1231) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:10:48.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:10:48.070+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:48.066+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:10:48.962+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:10:48.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:10:48.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:10:49.005+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.966 seconds
[2024-11-30T09:11:19.618+0000] {processor.py:161} INFO - Started process (PID=1258) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:11:19.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:11:19.631+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:19.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:11:21.064+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:21.050+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:11:21.075+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:11:21.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.518 seconds
[2024-11-30T09:11:51.657+0000] {processor.py:161} INFO - Started process (PID=1297) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:11:51.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:11:51.668+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:51.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:11:52.668+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:11:52.652+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:11:52.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:11:52.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.076 seconds
[2024-11-30T09:12:23.618+0000] {processor.py:161} INFO - Started process (PID=1330) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:12:23.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:12:23.627+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:23.626+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:12:24.775+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:24.761+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:12:24.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:12:24.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.215 seconds
[2024-11-30T09:12:55.422+0000] {processor.py:161} INFO - Started process (PID=1365) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:12:55.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:12:55.428+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:55.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:12:56.525+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:12:56.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:12:56.530+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:12:56.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.157 seconds
[2024-11-30T09:13:27.313+0000] {processor.py:161} INFO - Started process (PID=1392) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:13:27.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:13:27.322+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:27.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:13:28.521+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:28.509+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:13:28.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:13:28.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.249 seconds
[2024-11-30T09:13:59.021+0000] {processor.py:161} INFO - Started process (PID=1419) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:13:59.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:13:59.025+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:13:59.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:14:00.115+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:00.094+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:14:00.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:14:00.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.149 seconds
[2024-11-30T09:14:30.385+0000] {processor.py:161} INFO - Started process (PID=1443) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:14:30.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:14:30.394+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:30.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:14:31.967+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:14:31.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:14:31.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:14:32.037+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 1.665 seconds
[2024-11-30T09:15:02.665+0000] {processor.py:161} INFO - Started process (PID=1473) to work on /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:15:02.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/src/transform_data.py for tasks to queue
[2024-11-30T09:15:02.676+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:15:02.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:15:03.614+0000] {logging_mixin.py:188} INFO - [2024-11-30T09:15:03.601+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/src/transform_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/src/transform_data.py", line 11, in <module>
    GCS_BUCKET = Variable.get('GCS_BUCKET')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable GCS_BUCKET does not exist'
[2024-11-30T09:15:03.619+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/src/transform_data.py
[2024-11-30T09:15:03.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/src/transform_data.py took 0.999 seconds
